version: "3.1"
services:

  db:
    image: postgres:10-alpine
    container_name: pg01
    hostname: pg01
    volumes:
         - /media/amit/c759e8f9-933e-40a0-b74e-2aabbf8927d6/pg_data:/var/lib/postgresql/data
         - ./data/:/var/lib/postgresql/tmp_data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: amit4488
      POSTGRES_DB: espresso

  admin:
    image: adminer
    container_name: pg01-client
    hostname: pg01-client
    depends_on:
      - db
    ports:
      - 8080:8080

